base/urls.py
from django.contrib import admin
from django.urls import path, include
from base.views import principal, logout_user ,mostrar_pdf_ayuda
# para las iamgenes
from django.conf import settings
from django.conf.urls.static import static
# para la gestion de login y contraseña
from django.contrib.auth import views as auth_views
urlpatterns = [
    #gestion de login y contraseña
    path('',auth_views.LoginView.as_view(),name='inicio'),
    path('reiniciar/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('reiniciar/enviar',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reiniciar/completo',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',logout_user,name="logout"),
    
    path('admin/', admin.site.urls),
    path('inicio/', principal, name="index" ),
    path('usuarios/', include('usuarios.urls') ),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
    path('compra/', include('compra.urls')),
    path('proveedor/', include('proveedor.urls')),
   path('cliente/', include('cliente.urls')),
   path('ayuda/',mostrar_pdf_ayuda, name='ayuda'),


    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios.views import usuario_listar, usuario_crear, usuario_modificar, usuario_eliminar ,inactivos_listar

urlpatterns = [
    path('usuario/', usuario_listar, name="usuarios" ),
    path('usuario/inactivos', inactivos_listar, name="inactivos" ),
    path('usuario/crear/', usuario_crear, name="usuarios-crear" ),
    path('usuario/modificar/<int:pk>/', usuario_modificar, name="usuarios-modificar" ),
    path('usuario/eliminar/<int:pk>/', usuario_eliminar, name="usuarios-eliminar" ),
    

]

usuarios/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.exceptions import ValidationError
import re
def letras_validator(value):
    if not re.match("^[A-Za-zÁÉÍÓÚáéíóú ]+$", value):
        raise ValidationError('Este campo solo debe contener letras.')
    
def numeros_validator(value):
    if not re.match("^[0-9]+$", value):
        raise ValidationError('Este campo solo debe contener números.')
def unique_documento_validator(value):
    if Usuario.objects.filter(documento=value).exists():
           raise ValidationError('Este documento ya está registrado.')   

class Usuario(AbstractUser):
    groups = models.ManyToManyField(Group, blank=True, related_name="usuarios")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name='usuarios')
    nombre = models.CharField(max_length=45,verbose_name="Nombres", validators=[letras_validator])
    apellido = models.CharField(max_length=45,verbose_name="Apellidos", validators=[letras_validator]) 
    class TipoDocumento(models.TextChoices):
        CEDULA = 'CC', _("Cédula de Ciudadania")
        NIT='NIT',_("NIT")
        CEDULA_EXTRANJERIA='CE',_("Cédula de Extranjería")
    tipo_documento =models.CharField(max_length=20,choices=TipoDocumento.choices,verbose_name="Tipo de Documento")
    documento = models.CharField(max_length=10,verbose_name="Documento",validators=[numeros_validator, unique_documento_validator])
    class RH(models.TextChoices):
        OP='OP',_("O+")
        ON='ON',_("O-")
        AP='AP',_("A+")
        AN='AN',_("A-")
        BP='BP',_("B+")
        BN='BN',_("B-")
        ABP='ABP',_("AB+")
        ABN='ABN',_("AB-")
        
    rh= models.CharField(max_length=3,choices=RH.choices,verbose_name="Factor RH")
    class TipoUsuario(models.TextChoices):
        ADMINISTRADOR='A',_("Administrador")
        EMPLEADO = 'E', _("Empleado")
    tipoUsuario=models.CharField(max_length=2,choices=TipoUsuario.choices,verbose_name="tipoUsuario", default="Administrador")
    
    telefono=models.CharField(max_length=10,verbose_name="Teléfono",validators=[numeros_validator])
    direccion=models.CharField(max_length=45,verbose_name="Dirección", default="cra3 #4-5")
    class Estado(models.TextChoices):
        ACTIVO='1',_("Activo")
        INACTIVO='0',_("Inactivo")
    estado=models.CharField(max_length=1,choices=Estado.choices,default=Estado.ACTIVO,verbose_name="Estado")
   

                
    def __str__(self):
        return f"{self.nombre} {self.apellido} {self.username}"
    
    class Meta:
        verbose_name_plural = "Usuarios"

usuarios/forms.py
from django.core.files.uploadedfile import UploadedFile
from django.forms import ModelForm, widgets
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from usuarios.models import Usuario

class UsuarioCreationForm(UserCreationForm):
    
    TIPOS_USUARIO = [
        ('Administrador', 'Administrador'),  # Valor por defecto
        ('Empleado', 'Empleado'), 
        # ... Puedes añadir más opciones aquí
    ]
    nombre = forms.CharField(max_length=100, required=True,label="Nombres")
    apellido = forms.CharField(max_length=100, required=True,label="Apellidos")
    tipo_documento = forms.ChoiceField(choices= Usuario.TipoDocumento.choices, required=True,label="Tipo de documento")
    documento = forms.CharField(max_length=10, required=True)
    rh = forms.ChoiceField(choices= Usuario.RH.choices, required=True)
    telefono = forms.CharField(max_length=10, required=True)
    direccion =forms.CharField(max_length=100, required=True)
    TipoUsuario = forms.ChoiceField(choices=TIPOS_USUARIO, required=True,label="Tipo de usuario")

    class Meta:
        model = Usuario
        fields = ('TipoUsuario','nombre','apellido','tipo_documento','documento','rh','telefono','direccion', 'email', 'password1', 'password2' )
        exclude=["estado"]
        
        
    def clean(self):
        cleaned_data = super().clean()
        documento = cleaned_data.get('documento')
        telefono= cleaned_data.get('telefono')

        if documento and len(str(documento)) > 12:
            self.add_error('documento', "El documento no puede tener más de 12 dígitos")

        if telefono and len(str(telefono)) > 10:
            self.add_error('telefono_contacto', "El teléfono no puede tener más de 10 dígitos")
        return cleaned_data
    
    def __init__(self, *args, **kwargs):
        super(UsuarioCreationForm, self).__init__(*args, **kwargs)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password2')


    def clean_email(self):
        email = self.cleaned_data['email']
        if Usuario.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo electrónico ya está registrado.")
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Contraseña'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if not user.username:
            user.username = self.cleaned_data['documento']# Si el campo empleado_usuario no está presente, asigna el valor del campo documento
        user.is_superuser = 1
        if commit:
            user.save()
        return user




class UsuarioUpdateForm(ModelForm):
    
    class Meta:
        model = Usuario
        fields = ('nombre','apellido','telefono','direccion', 'email','estado' )
        exclude=["documento","rh"]
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'instance' in kwargs:
            instance = kwargs['instance']
            if instance.estado == Usuario.Estado.ACTIVO:
                self.fields['estado'].widget = forms.HiddenInput()

               
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = self.cleaned_data['estado']  # Cambiar el estado del usuario activo/inactivo
        if commit:
            user.save()
        return user
    

base/views.py
from django.shortcuts import redirect, render
from usuarios.models import Usuario
from producto.models import Producto
from venta.models import Venta
from compra.models import Compra
from proveedor.models import Proveedor
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from cliente.models import Cliente 
from django.shortcuts import render

@login_required
def principal(request):
    titulo="Bienvenido al Sistema"
    usuarios= Usuario.objects.all().count()
    producto=Producto.objects.all().count()
    ventas=Venta.objects.all().count()
    compras=Compra.objects.all().count()
    proveedors= Proveedor.objects.all().count()
    clientes = Cliente.objects.all().count()

    context={
        
        "usuarios":usuarios,
        "producto":producto,
        "ventas":ventas,
        "compras":compras,
        "proveedors": proveedors,
        "clientes":  clientes,
        "titulo":titulo,
        
    }
    return render(request, "index.html",context)
@login_required
def logout_user(request):
    logout(request)
    return redirect('inicio')

@login_required
def mostrar_pdf_ayuda(request):
    titulo="Ayuda"
    context = {
        "titulo":titulo,
    }
    return render(request, 'ayuda/ayuda/ayuda.html',context)

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from usuarios.models import Usuario
from usuarios.forms import UsuarioCreationForm,UsuarioUpdateForm
from django.contrib import messages
from django.urls import reverse, resolve
from django.urls import reverse
from . import urls
from django.core.paginator import Paginator, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.urls import reverse
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.core.mail import send_mail
from django.contrib.auth.forms import PasswordResetForm 



@login_required()
def usuario_crear(request):
    titulo = "Usuario"

    if request.method == 'POST':
        form = UsuarioCreationForm(request.POST)
        if form.is_valid():
            try:
                # Crear una instancia del modelo Usuario pero no guardarlo aún
                nuevo_usuario = form.save(commit=False)

                # Establecer el valor del campo tipoUsuario del modelo Usuario
                nuevo_usuario.tipoUsuario = form.cleaned_data['TipoUsuario']

                # Guardar el nuevo usuario con el valor del campo tipoUsuario asignado
                nuevo_usuario.save()

                # Obtener el token para restablecimiento de contraseña
                user = nuevo_usuario
                token = default_token_generator.make_token(user)

                # Construir la URL de restablecimiento de contraseña
                protocol = 'http'  # Puedes cambiarlo a 'https' si tu sitio usa SSL
                domain = request.META['HTTP_HOST']
                reset_url = reverse('password_reset_confirm', kwargs={'uidb64': urlsafe_base64_encode(force_bytes(user.pk)), 'token': token})

                # Construir el mensaje de correo
                email_content = f"Hola {user.username},\n\n"
                email_content += "Has solicitado restablecer tu contraseña. Haz clic en el siguiente enlace:\n\n"
                email_content += f"{protocol}://{domain}{reset_url}\n\n"
                email_content += "Si no solicitaste este restablecimiento de contraseña, ignora este correo.\n\n"
                email_content += "Gracias,\nEl equipo de TuNombreDeSitio"

                # Enviar el correo
                send_mail(
                    'Restablecimiento de contraseña',
                    email_content,
                    'noreply@example.com',
                    [user.email],
                    fail_silently=False,
                )

                messages.success(request, 'Usuario creado exitosamente. Se ha enviado un correo electrónico para restablecer la contraseña.')
                return redirect('usuarios')
            except IntegrityError as e:
                if 'UNIQUE constraint' in str(e):
                    messages.error(request, 'El nombre de usuario ya existe.')
                else:
                    messages.error(request, 'Error al crear el usuario: {}'.format(str(e)))
        else:
            messages.error(request, 'Error al crear el usuario')
    else:
        form = UsuarioCreationForm()

    context = {
        'titulo': titulo,
        'form': form,
    }

    return render(request, 'usuarios/usuarios/crear.html', context)

@login_required
def usuario_listar(request):
    titulo="Usuario"
    usuarios= Usuario.objects.all()
    context={
        "titulo":titulo,
        "usuarios":usuarios,
        "user": request.user
    }
    return render(request,"usuarios/usuarios/listar.html", context)

@login_required
def usuario_modificar(request,pk):
    titulo="Usuario"
    usuario= Usuario.objects.get(id=pk)
    
    if request.method== 'POST':
        form= UsuarioUpdateForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            messages.success(request, 'El formulario se ha enviado correctamente.')
            return redirect('usuarios')
    else:
        form= UsuarioUpdateForm(instance=usuario)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request,"usuarios/usuarios/modificar.html", context)

@login_required()
def usuario_eliminar(request, pk):
    usuario = Usuario.objects.get(id=pk)
    # Cambiar el estado del usuario a "0" (inactivo)
    usuario.estado = "0"
    usuario.is_active = usuario.estado != "0"
    usuario.save()
    return redirect('usuarios')
   

@login_required
def inactivos_listar(request):
    titulo="Usuario"
    inactivos= Usuario.objects.filter(estado="0")
    context={
        "titulo":titulo,
        "inactivos":inactivos,
        "user": request.user
    }
    return render(request,"usuarios/usuarios/inactivos.html", context)

base/templates/usuarios/usuarios/crear.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
{% if request.user.tipoUsuario == "Administrador" %}
<div class="formularios">
    <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-outline-warning" type="submit" value="Agregar {{titulo}}">
        <a href="{% url 'usuarios' %}" class="btn btn-outline-danger" data-url="{% url 'usuarios' %}" > Cancelar</a>
    </form>

</div>
{% endif %}

{% endblock contenido %}
    

base/templates/usuarios/usuarios/inactivos.html
{% extends 'partials/body.html' %}
<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/datatables_custom/bootstrap/css/bootstrap.min.css">

    <!--datables CSS básico-->
    <link rel="stylesheet" type="text/css" href="/static/datatables_custom/datatables/datatables.min.css"/>
    <!--datables estilo bootstrap 4 CSS-->  
    <link rel="stylesheet"  type="text/css" href="/static/datatables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css">
       <!--font awesome con CDN-->  
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>
{% block contenido %}
{% if request.user.tipoUsuario == "Administrador" %}
<div class="container-fluid m-5">
    <a href="{% url 'usuarios' %}" class="btn btn-success w-25">Usuarios Activos <i class="bi bi-person-check"></i></a>    
<img src="/static/img/logo1.png" alt="" class="logo" width="100px" high="100px">
</div>

<div class="container-fluid mb-5">
<table id="example" class="table table-hover ">
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Tipo de Documento</th>
            <th>Documento</th>
            <th>Rh</th>
            <th>Tipo Usuario</th>
            <th>Correo</th>
            <th>Teléfono</th>
            <th>Dirección</th>
            <th style="text-align: center;">Acciones</th>

        </tr>
    </thead>
    <tbody>
        
        {% for usuario in inactivos %}

        <tr> 
        

            
                <td>{{usuario.nombre}}</td>
                <td>{{usuario.apellido}}</td>
                <td>{{usuario.get_tipo_documento_display}}</td>
                <td>{{usuario.documento}}</td>
                <td>{{usuario.get_rh_display}}</td>
                <td>{{usuario.get_tipoUsuario_display}}</td>
                <td>{{usuario.email}}</td>
                <td>{{usuario.telefono}}</td>
                <td>{{usuario.direccion}}</td>
                <td style="text-align: center;">
                    <a class="btn btn-primary" title="Modificar" href="{% url 'usuarios-modificar' usuario.id %}"><i class="bi bi-pencil-square"></i></a>
                </td>

            </tr>

        {% endfor %}

    </tbody>
  </table>
</div>
<div class="container-fluid p-5">
 
  
</div>
<script src="/static/datatables_custom/jquery/jquery-3.3.1.min.js"></script>
 <script src="/static/datatables_custom/popper/popper.min.js"></script>
 <script src="/static/datatables_custom/bootstrap/js/bootstrap.min.js"></script>
   
 <!-- datatables JS -->
 <script type="text/javascript" src="/static/datatables_custom/datatables/datatables.min.js"></script>    
  
 <!-- para usar botones en datatables JS -->  
 <script src="/static/datatables_custom/datatables/Buttons-1.5.6/js/dataTables.buttons.min.js"></script>  
 <script src="/static/datatables_custom/datatables/JSZip-2.5.0/jszip.min.js"></script>    
 <script src="/static/datatables_custom/datatables/pdfmake-0.1.36/pdfmake.min.js"></script>    
 <script src="/static/datatables_custom/datatables/pdfmake-0.1.36/vfs_fonts.js"></script>
 <script src="/static/datatables_custom/datatables/Buttons-1.5.6/js/buttons.html5.min.js"></script>

 <!-- código JS propìo-->    
 <script type="text/javascript" src="/static/datatables_custom/main.js"></script>

{% endif %}

{% endblock contenido %}
    

base/templates/usuarios/usuarios/listar.html
{% extends 'partials/body.html' %}
<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/datatables_custom/bootstrap/css/bootstrap.min.css">

    <!--datables CSS básico-->
    <link rel="stylesheet" type="text/css" href="/static/datatables_custom/datatables/datatables.min.css"/>
    <!--datables estilo bootstrap 4 CSS-->  
    <link rel="stylesheet"  type="text/css" href="/static/datatables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css">
       <!--font awesome con CDN-->  
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>
{% block contenido %}
{% if request.user.tipoUsuario == "Administrador" %}
<div class="container-fluid m-5 d-flex flex-column mb-3">
<div class="">
    <a href="{% url 'inactivos' %}" class="btn btn-danger w-25">Usuarios Inactivos <i class="bi bi-person-fill-x"></i></a>    
<img src="/static/img/logo1.png" alt="" class="logo" width="100px" high="100px">
</div>
<div >
    <a href="{% url 'usuarios-crear' %}" class="btn btn-outline-light w-25">Crear {{titulo}}</a>

    </div>
</div>

<div class="container-fluid mb-5">
<table id="example" class="table table-hover ">
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Tipo de Documento</th>
            <th>Documento</th>
            <th>Rh</th>
            <th>Tipo Usuario</th>
            <th>Correo</th>
            <th>Teléfono</th>
            <th>Dirección</th>
            <th>Acciones</th>

        </tr>
    </thead>
    <tbody>
        
        {% for usuario in usuarios %}
        {% if usuario.nombre != "" and usuario.direccion != "cra3 #4-5" %}
        {% if usuario.estado != "0" %}

        <tr> 
        

            
                <td>{{usuario.nombre}}</td>
                <td>{{usuario.apellido}}</td>
                <td>{{usuario.get_tipo_documento_display}}</td>
                <td>{{usuario.documento}}</td>
                <td>{{usuario.get_rh_display}}</td>
                <td>{{usuario.get_tipoUsuario_display}}</td>
                <td>{{usuario.email}}</td>
                <td>{{usuario.telefono}}</td>
                <td>{{usuario.direccion}}</td>
                <td>
                 
               
                    <a type="button"  title="Inactivar" class="btnEliminar btn btn-danger" href="{% url 'usuarios-eliminar' usuario.id %}" onclick="return confirm('¿Está seguro de inactivar el {{ titulo|lower }}?')">
                        <i class="bi bi-person-fill-x"></i> </a>

                  
                    <a class="btn btn-primary"  title="Modificar" href="{% url 'usuarios-modificar' usuario.id %}"><i class="bi bi-pencil-square"></i></a>
                </td>

            </tr>
            {% endif %}
            {% endif %}

        {% endfor %}

    </tbody>
  </table>
</div>
<div class="container-fluid p-5">
 
  
</div>
<script src="/static/datatables_custom/jquery/jquery-3.3.1.min.js"></script>
 <script src="/static/datatables_custom/popper/popper.min.js"></script>
 <script src="/static/datatables_custom/bootstrap/js/bootstrap.min.js"></script>
   
 <!-- datatables JS -->
 <script type="text/javascript" src="/static/datatables_custom/datatables/datatables.min.js"></script>    
  
 <!-- para usar botones en datatables JS -->  
 <script src="/static/datatables_custom/datatables/Buttons-1.5.6/js/dataTables.buttons.min.js"></script>  
 <script src="/static/datatables_custom/datatables/JSZip-2.5.0/jszip.min.js"></script>    
 <script src="/static/datatables_custom/datatables/pdfmake-0.1.36/pdfmake.min.js"></script>    
 <script src="/static/datatables_custom/datatables/pdfmake-0.1.36/vfs_fonts.js"></script>
 <script src="/static/datatables_custom/datatables/Buttons-1.5.6/js/buttons.html5.min.js"></script>

 <!-- código JS propìo-->    
 <script type="text/javascript" src="/static/datatables_custom/main.js"></script>

{% endif %}

{% endblock contenido %}
    

base/templates/usuarios/usuarios/modificar.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
{% if request.user.tipoUsuario == "Administrador" %}
<div class="formularios"> 
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-outline-success" type="submit" value="Modificar {{titulo}}">
            <a href="{% url 'usuarios' %}" class="btn btn-outline-danger" data-url="{% url 'usuarios' %}" > Cancelar</a>
        </form>
    </div>
    {% endif %}

{% endblock contenido %}